services:
  db:
    image: postgres
    restart: always
    ports:
     - "5434:5432"
    environment:
      POSTGRES_PASSWORD: pass123
  test-db:
    image: postgres
    restart: always
    ports:
     - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass123
  dbm:
    image: mongo
    restart: always
    ports:
     - "27017:27017"
    environment:
      MONGODB_DATABASE: nest-course
