@host = http://localhost:3000
@limit = 1
@offset = 3

GET {{host}}/coffees?limit={{limit}}&offset={{offset}}

###
@id = 1
GET {{host}}/coffees/{{id}}

###

POST {{host}}/coffees
Content-Type: application/json

{
    "name": "Old Florida Roast",
    "brand": "Buddy Brew"
}
###

PATCH {{host}}/coffees/{{id}}
Content-Type: application/json

{
    "name": "Old Florida Roast",
    "brand": "Buddy Brew"
}
###

DELETE {{host}}/coffees/{{id}}
