@host = http://localhost:3000
@limit = 1
@offset = 3

###
#Get All
###
GET {{host}}/coffees?limit={{limit}}&offset={{offset}}

###
#Get One
###
@id = 2
GET {{host}}/coffees/{{id}}

###
#Create
###
POST {{host}}/coffees
Content-Type: application/json

{
    "name": "Old Florida Roast3",
    "brand": "Buddy Brew",
    "flavors": ["one"]
}
###
#Uptate
###
PATCH {{host}}/coffees/{{id}}
Content-Type: application/json

{
    "name": "Old Florida Roast2",
    "brand": "Buddy Brew"
}
###
#delete
###
DELETE {{host}}/coffees/{{id}}
