@host = http://localhost:3000
@limit = 3
@offset = 1

@token = 123456O

###
#Get All
###
GET {{host}}/
Authorization: {{token}}


###
#Get All
###
GET {{host}}/coffees?limit={{limit}}&offset={{offset}}

###
#Get One
###
@id = 1
GET {{host}}/coffees/{{id}}
Content-Type: application/json
Authorization: {{token}}

###
#Create
###
POST {{host}}/coffees
Content-Type: application/json
Authorization: {{token}}


{
    "name": "Old Florida Roast4",
    "brand": "Buddy Brew",
    "flavors": ["ones", "twos", "threes"]
}
###
#Uptate
###
PATCH {{host}}/coffees/{{id}}
Content-Type: application/json

{
    "name": "Old Florida Roast2",
    "brand": "Buddy Brew"
}
###
#delete
###
DELETE {{host}}/coffees/{{id}}
